### ISSUE TITLE
Shield Variant Recipes aren't working

### ISSUE THREAD

**Issue by pommellie** [pnk2u/More-Shield-Variants#1]
The recipe for Spruce Shield is working fine (using the default recipe for the Shield), but the other variants of the shield are using only a single ingot (which only turns into 9 iron nuggets). Is this something on my end that I can fix or?

**Comment by pnk2u** [comment]
Oh, I'm sorry, I must've overlooked something. Please let me know, what version of the game is this on?

**Comment by pnk2u** [comment]
Ok, nevermind, I found the problem and it affects all versions. I'll upload a fixed version in a few hours once I'm back home.

**Comment by pnk2u** [comment]
Thanks for reporting this issue. I just uploaded version 1.1.0 to Modrinth and Curseforge. I hope that fixes it - if it does, feel free to close this issue. (:

**Comment by pommellie** [comment]
I am so sorry! I never got the notifs for the responses! I am glad you managed to find the issue without needing my version after all. I will download the fixed version and let you know!

**Comment by pommellie** [comment]
Works beautifully now! The crafting recipes are there and work as intended! Thank you so much for your help with this!
