### ISSUE TITLE
All shield recipes all default to spruce shield.

### ISSUE THREAD

**Issue by TheMasterBlaster** [pnk2u/More-Shield-Variants#2]
Minecraft 1.21
cloth-config 15.0.128
Fabric Loader 0.16.0
quad 1.2.7
More Shield Variants 1.1.0

I grabbed any part of the console log that had the word shield in it. I hope that's enough info.

[lolmsv console_errors.txt](https://github.com/user-attachments/files/16384287/lolmsv.console_errors.txt)

![lolmsv result](https://github.com/user-attachments/assets/9a2ae6a2-6914-4806-ad80-a55e6225fe08)

**Comment by pnk2u** [comment]
Hi, thanks for reporting this issue, unfortunately, I cannot reproduce it at all. Are you sure, there is no other/older version of More Shield Variants in your mod folder? Also, what version of Fabric API do you have installed?

**Comment by TheMasterBlaster** [comment]
Just got a chance to check. The Fabric API version is 0.100.7, and I have confirmed I only have just the one version of MSV, and it is indeed version 1.1.0.

After trying Singleplayer, it seems to be an issue with something on the server(?) as Singleplayer works as intended.

**Comment by pnk2u** [comment]
Ah, I see, thank you. Yes, that makes sense. Now, does this happen, even with both the player and the server having the mod installed? Or is it a problem that arises when the server has the mod installed but the player doesn't?

I don't know why yet, but it seems that the vanilla shield recipe can't be overwritten like in single player, which makes it in turn overwrite all variant shield recipes. A quick solution I could offer to you would be to add a hidden recipe like e.g. filling the two empty spaces of the recipe with two more planks which makes it not trigger the vanilla shield recipe and avoids the issue you're having, would you be interested in that? If so, I'd happily release an update implementing that. (:

**Comment by TheMasterBlaster** [comment]
I have only tried when both the server and client had the mod installed. I didn't think a client could join a server when said client was missing a mod that added items/blocks when the server had it.

I'd appreciate a temp fix/workaround whenever you have the time.

I really appreciate the effort and time you put into your mods! :)

**Comment by pnk2u** [comment]
Thanks for the kind words! (:

The mentioned workaround recipes have been added in version 1.1.1 that I've just uploaded to Modrinth and CF. Again, as mentioned, these recipes fill the two remaining empty slots of the normal shield recipes. The changelog also explains this.
I really hope it works, please let me know if it does! (:

**Comment by TheMasterBlaster** [comment]
I updated my server and client to version 1.1.1 and it seems there is no change when on the server.

On Singleplayer, I can see the spruce shield that can be made with any type of planks, recipes for all shields using the normal shield recipe style, and the recipes for all shields using the two empty slots.

**Comment by pnk2u** [comment]
That is really unfortunate and I'm very sorry but it seems I'm out of my element here for now (as my knowledge is very singleplayer focused) I will come back to you as soon as I find a way to do what is needed here.

But just so I have all the relevant information: Everything but the Variant Shield recipes works? The items load in properly (e.g. Creative Item Menu), can be used properly (as shields) and look as expected?

**Comment by TheMasterBlaster** [comment]
Trying to put any Shield variant(other than spruce) into my inventory seems to cause the client to disconnect.
![lolmsv_ConnectionLost](https://github.com/user-attachments/assets/51ac0924-f1c2-43cb-987a-5c56350f41c0)

Using the give command
![lolmsv_GiveCommand](https://github.com/user-attachments/assets/fac13ea2-e3e4-455e-9965-a791cc51273b)

**Comment by pnk2u** [comment]
Yeah, I found similar things, it doesn't load the items at all.
Thanks for the help.

**Comment by NemoNotFound** [comment]
@TheMasterBlaster I found the issue. You'll soon be able to play the mod on servers :D

**Comment by pnk2u** [comment]
Yup, exactly, thanks to @NemoNotFound the issue has been fixed in version 1.2.0 which is now available. Let me know if it works for you so I then can close this issue or feel free to close it yourself in that case. (:

**Comment by TheMasterBlaster** [comment]
Looks like that fix worked great! Thanks for the help @NemoNotFound & @pnk2u! I love the hard work you both put into your mods! <3
