### ISSUE TITLE
Shields looks the same 1.21

### ISSUE THREAD

**Issue by makumaku1974** [pnk2u/More-Shield-Variants#3]
![image](https://github.com/user-attachments/assets/d9a90335-0c05-47cb-bc75-448223cd05e0)
![image](https://github.com/user-attachments/assets/0c0287e8-2304-4d37-8c1b-4416f4557455)

**Comment by makumaku1974** [comment]
I've update EMI but i dont think EMI has got to do with this problem. A full plank shield would be a different texture while the default shield recipe be the standard plank texture.

**Comment by pnk2u** [comment]
Ah, that is actually intended behaviour as the full plank recipe is just meant as a fallback for when the mod in rare cases fails to overwrite the vanilla recipe. They are supposed to be the same texture as they are the same item for both recipes. To change textures of the shields, use mod menu, there you can decide for each shield individually which texture you would like it to use. Sorry for the misunderstanding.

**Comment by makumaku1974** [comment]
> Ah, that is actually intended behaviour as the full plank recipe is just meant as a fallback for when the mod in rare cases fails to overwrite the vanilla recipe. They are supposed to be the same texture as they are the same item for both recipes. To change textures of the shields, use mod menu, there you can decide for each shield individually which texture you would like it to use. Sorry for the misunderstanding.

Thanks for replying. I was very at first why but oh well.
