### ISSUE TITLE
shield texture missing!

### ISSUE THREAD

**Issue by ghost** [pnk2u/More-Shield-Variants#9]
the texture is missing! i can see the nametag when i hover over it and even put it in my offhand.
i have rei mod, so it says the number of components, like this:

Oak Shield
lolmsv:oak_shield
13 component(s) 

please help!
![image_2024-12-08_145657231](https://github.com/user-attachments/assets/61f33851-8ffb-4cd1-8dd4-d438bed441e3)

**Comment by pnk2u** [comment]
Please tell me what Minecraft version and what More Shield Variants version you're using. Please also send me you're "latest.log" file which is located in "~/.minecraft/logs/latest.log".

**Comment by pnk2u** [comment]
Another thing, does this only happen with the Oak Shield or all shields? (If you can test it in a new save in Creative mode.)

**Comment by pnk2u** [comment]
Since I heard nothing back, I will close this issue for now. Feel free to re-open it if you have problems with this issue again and please then give me more information as described above.
